// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: review/v1/review.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建评价请求
type CreateReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`             // 用户ID
	OrderId       int64                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`           // 订单ID
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`               // 评分
	ServiceScore  int32                  `protobuf:"varint,4,opt,name=serviceScore,proto3" json:"serviceScore,omitempty"` // 服务评分
	ExpressScore  int32                  `protobuf:"varint,5,opt,name=expressScore,proto3" json:"expressScore,omitempty"` // 物流评分
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`            // 评价内容
	PicInfo       string                 `protobuf:"bytes,7,opt,name=picInfo,proto3" json:"picInfo,omitempty"`            // 评价图片
	VideoInfo     string                 `protobuf:"bytes,8,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"`        // 评价视频
	VoiceInfo     string                 `protobuf:"bytes,9,opt,name=voiceInfo,proto3" json:"voiceInfo,omitempty"`        // 评价语音
	Anonymous     bool                   `protobuf:"varint,10,opt,name=anonymous,proto3" json:"anonymous,omitempty"`      // 是否匿名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewReq) Reset() {
	*x = CreateReviewReq{}
	mi := &file_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewReq) ProtoMessage() {}

func (x *CreateReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewReq.ProtoReflect.Descriptor instead.
func (*CreateReviewReq) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReviewReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateReviewReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateReviewReq) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *CreateReviewReq) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *CreateReviewReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReviewReq) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *CreateReviewReq) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

func (x *CreateReviewReq) GetVoiceInfo() string {
	if x != nil {
		return x.VoiceInfo
	}
	return ""
}

func (x *CreateReviewReq) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

// 创建评价响应
type CreateReviewRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=reviewId,proto3" json:"reviewId,omitempty"` // 评价ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRsp) Reset() {
	*x = CreateReviewRsp{}
	mi := &file_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRsp) ProtoMessage() {}

func (x *CreateReviewRsp) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRsp.ProtoReflect.Descriptor instead.
func (*CreateReviewRsp) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRsp) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

// 回复评价请求
type ReplyReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=reviewId,proto3" json:"reviewId,omitempty"`  // 评价ID
	StoreId       int64                  `protobuf:"varint,2,opt,name=storeId,proto3" json:"storeId,omitempty"`    // 商家ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`     // 回复内容
	PicInfo       string                 `protobuf:"bytes,4,opt,name=picInfo,proto3" json:"picInfo,omitempty"`     // 回复图片
	VideoInfo     string                 `protobuf:"bytes,5,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"` // 回复视频
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewReq) Reset() {
	*x = ReplyReviewReq{}
	mi := &file_review_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewReq) ProtoMessage() {}

func (x *ReplyReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewReq.ProtoReflect.Descriptor instead.
func (*ReplyReviewReq) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyReviewReq) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReplyReviewReq) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ReplyReviewReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyReviewReq) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *ReplyReviewReq) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

// 回复评价响应
type ReplyReviewRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"` // 回复评价ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewRsp) Reset() {
	*x = ReplyReviewRsp{}
	mi := &file_review_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewRsp) ProtoMessage() {}

func (x *ReplyReviewRsp) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewRsp.ProtoReflect.Descriptor instead.
func (*ReplyReviewRsp) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyReviewRsp) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

var File_review_v1_review_proto protoreflect.FileDescriptor

const file_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x16review/v1/review.proto\x12\rapi.review.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x86\x03\n" +
	"\x0fCreateReviewReq\x12\x1f\n" +
	"\x06userId\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12!\n" +
	"\aorderId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12'\n" +
	"\x05score\x18\x03 \x01(\x05B\x11\xfaB\x0e\x1a\f0\x000\x010\x020\x030\x040\x05R\x05score\x125\n" +
	"\fserviceScore\x18\x04 \x01(\x05B\x11\xfaB\x0e\x1a\f0\x000\x010\x020\x030\x040\x05R\fserviceScore\x125\n" +
	"\fexpressScore\x18\x05 \x01(\x05B\x11\xfaB\x0e\x1a\f0\x000\x010\x020\x030\x040\x05R\fexpressScore\x12$\n" +
	"\acontent\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\b\x18\xff\x01R\acontent\x12\x18\n" +
	"\apicInfo\x18\a \x01(\tR\apicInfo\x12\x1c\n" +
	"\tvideoInfo\x18\b \x01(\tR\tvideoInfo\x12\x1c\n" +
	"\tvoiceInfo\x18\t \x01(\tR\tvoiceInfo\x12\x1c\n" +
	"\tanonymous\x18\n" +
	" \x01(\bR\tanonymous\"-\n" +
	"\x0fCreateReviewRsp\x12\x1a\n" +
	"\breviewId\x18\x01 \x01(\x03R\breviewId\"\xb6\x01\n" +
	"\x0eReplyReviewReq\x12#\n" +
	"\breviewId\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\x12!\n" +
	"\astoreId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreId\x12$\n" +
	"\acontent\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xff\x01R\acontent\x12\x18\n" +
	"\apicInfo\x18\x04 \x01(\tR\apicInfo\x12\x1c\n" +
	"\tvideoInfo\x18\x05 \x01(\tR\tvideoInfo\"*\n" +
	"\x0eReplyReviewRsp\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId2\xd9\x01\n" +
	"\x06Review\x12e\n" +
	"\fCreateReview\x12\x1e.api.review.v1.CreateReviewReq\x1a\x1e.api.review.v1.CreateReviewRsp\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/review\x12h\n" +
	"\vReplyReview\x12\x1d.api.review.v1.ReplyReviewReq\x1a\x1d.api.review.v1.ReplyReviewRsp\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/review/replyB2\n" +
	"\rapi.review.v1P\x01Z\x1freview-service/api/review/v1;v1b\x06proto3"

var (
	file_review_v1_review_proto_rawDescOnce sync.Once
	file_review_v1_review_proto_rawDescData []byte
)

func file_review_v1_review_proto_rawDescGZIP() []byte {
	file_review_v1_review_proto_rawDescOnce.Do(func() {
		file_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)))
	})
	return file_review_v1_review_proto_rawDescData
}

var file_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_review_v1_review_proto_goTypes = []any{
	(*CreateReviewReq)(nil), // 0: api.review.v1.CreateReviewReq
	(*CreateReviewRsp)(nil), // 1: api.review.v1.CreateReviewRsp
	(*ReplyReviewReq)(nil),  // 2: api.review.v1.ReplyReviewReq
	(*ReplyReviewRsp)(nil),  // 3: api.review.v1.ReplyReviewRsp
}
var file_review_v1_review_proto_depIdxs = []int32{
	0, // 0: api.review.v1.Review.CreateReview:input_type -> api.review.v1.CreateReviewReq
	2, // 1: api.review.v1.Review.ReplyReview:input_type -> api.review.v1.ReplyReviewReq
	1, // 2: api.review.v1.Review.CreateReview:output_type -> api.review.v1.CreateReviewRsp
	3, // 3: api.review.v1.Review.ReplyReview:output_type -> api.review.v1.ReplyReviewRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_review_v1_review_proto_init() }
func file_review_v1_review_proto_init() {
	if File_review_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_v1_review_proto_goTypes,
		DependencyIndexes: file_review_v1_review_proto_depIdxs,
		MessageInfos:      file_review_v1_review_proto_msgTypes,
	}.Build()
	File_review_v1_review_proto = out.File
	file_review_v1_review_proto_goTypes = nil
	file_review_v1_review_proto_depIdxs = nil
}
