// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/review/v1/review_error.proto

// 定义包名

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_REVIEW_CREATE_FAILED  ErrorReason = 0 // 评价创建失败
	ErrorReason_REVIEW_NOT_FOUND      ErrorReason = 1 // 评价不存在
	ErrorReason_REVIEW_ALREADY_EXISTS ErrorReason = 2 // 评价已存在
	ErrorReason_REVIEW_INVALID_PARAMS ErrorReason = 3 // 评价参数无效
	ErrorReason_REVIEW_INTERNAL_ERROR ErrorReason = 4 // 评价内部错误
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "REVIEW_CREATE_FAILED",
		1: "REVIEW_NOT_FOUND",
		2: "REVIEW_ALREADY_EXISTS",
		3: "REVIEW_INVALID_PARAMS",
		4: "REVIEW_INTERNAL_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"REVIEW_CREATE_FAILED":  0,
		"REVIEW_NOT_FOUND":      1,
		"REVIEW_ALREADY_EXISTS": 2,
		"REVIEW_INVALID_PARAMS": 3,
		"REVIEW_INTERNAL_ERROR": 4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_review_v1_review_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_review_v1_review_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_review_v1_review_error_proto_rawDescGZIP(), []int{0}
}

var File_api_review_v1_review_error_proto protoreflect.FileDescriptor

const file_api_review_v1_review_error_proto_rawDesc = "" +
	"\n" +
	" api/review/v1/review_error.proto\x12\rapi.review.v1\x1a\x13errors/errors.proto*\xb2\x01\n" +
	"\vErrorReason\x12\x1e\n" +
	"\x14REVIEW_CREATE_FAILED\x10\x00\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x10REVIEW_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x15REVIEW_ALREADY_EXISTS\x10\x02\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x15REVIEW_INVALID_PARAMS\x10\x03\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x15REVIEW_INTERNAL_ERROR\x10\x04\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B2\n" +
	"\rapi.review.v1P\x01Z\x1freview-service/api/review/v1;v1b\x06proto3"

var (
	file_api_review_v1_review_error_proto_rawDescOnce sync.Once
	file_api_review_v1_review_error_proto_rawDescData []byte
)

func file_api_review_v1_review_error_proto_rawDescGZIP() []byte {
	file_api_review_v1_review_error_proto_rawDescOnce.Do(func() {
		file_api_review_v1_review_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_review_v1_review_error_proto_rawDesc), len(file_api_review_v1_review_error_proto_rawDesc)))
	})
	return file_api_review_v1_review_error_proto_rawDescData
}

var file_api_review_v1_review_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_review_v1_review_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.review.v1.ErrorReason
}
var file_api_review_v1_review_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_review_v1_review_error_proto_init() }
func file_api_review_v1_review_error_proto_init() {
	if File_api_review_v1_review_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_review_v1_review_error_proto_rawDesc), len(file_api_review_v1_review_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_review_v1_review_error_proto_goTypes,
		DependencyIndexes: file_api_review_v1_review_error_proto_depIdxs,
		EnumInfos:         file_api_review_v1_review_error_proto_enumTypes,
	}.Build()
	File_api_review_v1_review_error_proto = out.File
	file_api_review_v1_review_error_proto_goTypes = nil
	file_api_review_v1_review_error_proto_depIdxs = nil
}
